# Generated by Django 5.2.5 on 2025-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jikwon",
            fields=[
                ("jikwonno", models.AutoField(primary_key=True, serialize=False)),
                ("jikwonname", models.CharField(blank=True, max_length=50, null=True)),
                ("jikwonibsail", models.DateField(blank=True, null=True)),
                ("jikwonpay", models.IntegerField(blank=True, null=True)),
                ("jikwonjik", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "jikwon",
                "managed": False,
            },
        ),
    ]
