# Generated by Django 5.2 on 2025-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_birth', models.IntegerField(blank=True, db_column='Year_Birth', null=True)),
                ('education', models.IntegerField(blank=True, db_column='Education', null=True)),
                ('income', models.IntegerField(blank=True, db_column='Income', null=True)),
                ('kidhome', models.IntegerField(blank=True, db_column='Kidhome', null=True)),
                ('teenhome', models.IntegerField(blank=True, db_column='Teenhome', null=True)),
                ('recency', models.IntegerField(blank=True, db_column='Recency', null=True)),
                ('mntwines', models.IntegerField(blank=True, db_column='MntWines', null=True)),
                ('mntfruits', models.IntegerField(blank=True, db_column='MntFruits', null=True)),
                ('mntmeatproducts', models.IntegerField(blank=True, db_column='MntMeatProducts', null=True)),
                ('mntfishproducts', models.IntegerField(blank=True, db_column='MntFishProducts', null=True)),
                ('mntsweetproducts', models.IntegerField(blank=True, db_column='MntSweetProducts', null=True)),
                ('mntgoldprods', models.IntegerField(blank=True, db_column='MntGoldProds', null=True)),
                ('numdealspurchases', models.IntegerField(blank=True, db_column='NumDealsPurchases', null=True)),
                ('numwebpurchases', models.IntegerField(blank=True, db_column='NumWebPurchases', null=True)),
                ('numcatalogpurchases', models.IntegerField(blank=True, db_column='NumCatalogPurchases', null=True)),
                ('numstorepurchases', models.IntegerField(blank=True, db_column='NumStorePurchases', null=True)),
                ('numwebvisitsmonth', models.IntegerField(blank=True, db_column='NumWebVisitsMonth', null=True)),
                ('acceptedcmp1', models.IntegerField(blank=True, db_column='AcceptedCmp1', null=True)),
                ('acceptedcmp2', models.IntegerField(blank=True, db_column='AcceptedCmp2', null=True)),
                ('acceptedcmp3', models.IntegerField(blank=True, db_column='AcceptedCmp3', null=True)),
                ('acceptedcmp4', models.IntegerField(blank=True, db_column='AcceptedCmp4', null=True)),
                ('acceptedcmp5', models.IntegerField(blank=True, db_column='AcceptedCmp5', null=True)),
                ('complain', models.IntegerField(blank=True, db_column='Complain', null=True)),
                ('response', models.IntegerField(blank=True, db_column='Response', null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Jikwon',
        ),
    ]
